version: '3.8'

services:
  mongodb:
    image: mongo
    ports:
    - 27017:27017
  link-inspection-url-inspection-jest:
    build:
      context: ../
      dockerfile: ci/Dockerfile.test
    depends_on:
    - mongodb
