name: Fly Deploy

on: 
  push:
    branches:
      - '*'
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: flyctl deploy
        working-directory: backend-api
        run: flyctl deploy --remote-only
