name: CI

on: [push]

jobs:
  changes:
    name: Detect Changes in folder
    runs-on: ubuntu-latest
    outputs:
      names: ${{ steps.filter.outputs.changes }}
    steps:
    - uses: actions/checkout@v3
    - name: Detect Changes
      uses: dorny/paths-filter@v2
      id: filter
      with:
        base: ${{ github.ref }}
        filters: |
          backend-api:
            - 'backend-api/**'
  unit-test:
    needs: changes
    if: ${{ needs.changes.outputs.names == '["backend-api"]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        working-directory: backend-api
        run: npm install
      - name: Run test
        working-directory: backend-api
        run: npm run test:unit
  integration-test:
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run integration test
        working-directory: backend-api
        run: docker-compose -f ci/docker-compose.test.yml up --exit-code-from link-inspection-backend-jest
  deploy:
    needs: integration-test
    if: github.ref == 'refs/heads/main'
    name: Deploy app
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: flyctl deploy
        working-directory: backend-api
        run: flyctl deploy --remote-only
